### ISSUE TITLE
No current row highlight

### ISSUE THREAD

**Issue by shanet** [malcolmstill/thunner#3]
I'm not sure if it's a bug, or there is just no highlighting of the currently selected row, but it makes navigation very difficult. The screenshot below was taken on Kubuntu 12.04 with Python 2.7.3.

![prob_7](https://f.cloud.github.com/assets/1159147/35620/23e08676-5232-11e2-9498-2f2752b3c2d6.png)

**Comment by malcolmstill** [comment]
Have you defined colours in your ~/.thunnerrc? As a minimum you probably need to set a colour for 'current-item' which controls the colour for the current row. I'll update the README to reflect this.

I should really have it draw in reverse video mode if no colour is defined; let me look in to this.

**Comment by shanet** [comment]
@mstill I see, I was just using the example config from the README.

I added `assign mycolor current-item` to my .thunnerrc and the highlight color is now there. Thanks for the help!

The reverse video mode would be helpful, or even inverting the color of the text and background of the selected row.
