### ISSUE TITLE
Playlist error

### ISSUE THREAD

**Issue by bassnode** [malcolmstill/thunner#9]
Upon starting up thunner, I get the following errors.  The app never loads.  Is it just me...?

```
$  python --version
Python 2.7.2
$ ./thunner
A traceback follows: Traceback (most recent call last):
File: "/Library/Python/2.7/site-packages/gmusicapi-1.1.0-py2.7.egg/gmusicapi/protocol/shared.py", line 226, in perform cls.validate(response, msg)
File "/Library/Python/2.7/site-packages/gmusicapi-1.1.0-py2.7.egg/gmusicapi/protocol/webclient.py", line 91, in validate
return validictory.validate(msg, cls._res_schema)
File "build/bdist.macosx-10.8-intel/egg/validictory/__init__.py", line 31, in validate
return v.validate(data, schema)
File "build/bdist.macosx-10.8-intel/egg/validictory/validator.py", line 559, in validate
self._validate(data, schema)
File "build/bdist.macosx-10.8-intel/egg/validictory/validator.py", line 562, in _validate
self.__validate("_data", {"_data": data}, schema)
File "build/bdist.macosx-10.8-intel/egg/validictory/validator.py", line 593, in __validate
newschema.get(schemaprop))
File "build/bdist.macosx-10.8-intel/egg/validictory/validator.py", line 223, in validate_properties
properties.get(eachProp))
File "build/bdist.macosx-10.8-intel/egg/validictory/validator.py", line 593, in __validate
newschema.get(schemaprop))
File "build/bdist.macosx-10.8-intel/egg/validictory/validator.py", line 266, in validate_items
(fieldname, old_error), fieldname, e.value)
ValidationException: Failed to validate field 'playlist' list schema: additional property 'origin' not defined by 'properties' are not allowed in list item
2013-05-08 17:46:33,507 - gmusicapi.Webclient1 (shared:238) [ERROR]: the following response format for GetLibrarySongs was not recognized.
If there has not been a compatibility update reported[here](http://goo.gl/jTKNb), please [create an issue](http://goo.gl/qbAW8) that includes the following raw response:
{u'playlist': [{u'origin': [], u'rating': 0, u'lastPlayed': 1349279134551528, u'disc': 0, u'matchedId': u'', u'composer': u'', u'year': 2007, u'id': u'5b1432a8-039b-3ded-a51a-5ef3fbf9d41e', u'subjectToCuration': False, u'album': u'Squanch', u'title': u'CheeseHOG', u'recentTimestamp': 1349279134544000, u'deleted': False, u'albumArtist': u'', u'type': 2, u'titleNorm': u'cheesehog', u'track': 0, u'albumArtistNorm': u'', u'totalTracks': 0, u'beatsPerMinute': 0, u'genre': u'Electronic', u'playCount': 1, u'creationDate': 1349220454665164, u'bitrate': 320, u'comment': u'', u'name': u'CheeseHOG', u'albumNorm': u'squanch', u'artist': u'Bil Bless', u'url': u'', u'totalDiscs': 0, u'artistMatchedId': u'Atsi4kwj44aojhturl4xwsp5qky', u'durationMillis': 242000, u'artistNorm': u'bil bless'} ...

[SNIP - loads more JSON]

Traceback (most recent call last):
  File "./thunner", line 446, in <module>
    main()
  File "./thunner", line 300, in main
    playlists = list_playlists(api,playlist_ids)
  File "./thunner", line 247, in list_playlists
    playlists.append( { "name":name, "subtree":api.get_playlist_songs(pid), "subtreeline":0 } )
  File "/Library/Python/2.7/site-packages/gmusicapi-1.1.0-py2.7.egg/gmusicapi/clients.py", line 670, in get_playlist_songs
    res = self._make_call(webclient.GetPlaylistSongs, playlist_id)
  File "/Library/Python/2.7/site-packages/gmusicapi-1.1.0-py2.7.egg/gmusicapi/clients.py", line 85, in _make_call
    return protocol.perform(self.session, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/gmusicapi-1.1.0-py2.7.egg/gmusicapi/protocol/shared.py", line 221, in perform
    log.debug(cls.filter_response(msg))
  File "/Library/Python/2.7/site-packages/gmusicapi-1.1.0-py2.7.egg/gmusicapi/protocol/webclient.py", line 422, in filter_response
    filtered['playlist'] = ["<%s songs>" % len(filtered['playlist'])]
KeyError: 'playlist'
```

**Comment by l0neJT** [comment]
I received an identical error to that listed in your traceback. A little digging revealed lines 247 and 249 pass the variable pid which is NOT the playlist ID but a list containing a single element with the playlist ID. Try re-writing both lines:

playlists.append( { "name":name, "subtree":api.get_playlist_songs(pid[0]), "subtreeline":0 } )

Probably not the cleanest solution, but it works.

**Comment by bassnode** [comment]
@l0neJT thanks - that got me past the bootstrapping phase so I can now see the UI.  Unfortunately, the arrow keys don't work and when I hit enter, I get a stack trace.  oh well :panda_face:

**Comment by bassnode** [comment]
FWIW to anyone else having this issue, @reggna fixed the issue in this [fork](https://github.com/reggna/thunner).

**Comment by malcolmstill** [comment]
@bassnode, which terminal emulator are you using?

**Comment by bassnode** [comment]
@mstill bash in iTerm on OSX 10.8.4.

I pulled this repo with your latest changes and get this error:

```
$ ./thunner 
Traceback (most recent call last):
  File "./thunner", line 442, in <module>
    main()
  File "./thunner", line 376, in main
    playing = play(api.get_stream_urls(song['id'])[0])
AttributeError: 'Webclient' object has no attribute 'get_stream_urls'
```

**Comment by malcolmstill** [comment]
@bassnode I've just made some changes so it should play now without that error. I was using the dev branch of the API which seems to be using get_stream_urls whereas the current release is still using get_stream_url.

The arrow keys are a separate issue. I don't suppose this works for you: http://major.io/2007/05/31/arrow-keys-in-iterm-not-working-in-vivim/ ?

**Comment by bassnode** [comment]
@mstill Yup - seems fixed now, thanks!

Now that it doesn't crash, I can see it's not that the arrows keys don't work, it's that there is no visual feedback showing me where my cursor is.  That was fixed here: https://github.com/reggna/thunner/commit/b5037165e028a0ce84c08531bec006e87b27fad3
...might be worth considering as the UI is very hard to navigate otherwise.

**Comment by malcolmstill** [comment]
@bassnode Currently you basically need to have a colour terminal with colours set up in your ~/.thunnerrc. As a minimum, assign a color to "current-item". What version of iTerm are you running?

**Comment by malcolmstill** [comment]
@bassnode I had tried iTerm 0.10 but couldn't convince it didn't seem to pick up colours, nor could I change the display profile. That version seems to be out-of-date, see: http://superuser.com/questions/262592/select-display-profiles-in-iterm-for-os-x). Installing iTerm2 seemed to fix the issue. You could try that?

**Comment by bassnode** [comment]
I defined the color setting in my .thunnerrc and it now highlights the current item (although the bgcolor definition doesn't seem to have any effect):

```
color mycolors yellow green                                                                                                                                     
assign mycolors current-item
```

FWIW, I was actually using iTerm2 (ver. 1.0.0.20130622).  I've also tried it with OSX's default Terminal.app.  Both terminals support color as I have colors setup for my prompt, file listings, etc.

```
~/code/thunner on master*
$ echo $TERM
xterm-256color
```

Anyway - think this is all sorted.  Thanks for looking into it.  Perhaps there should be a bit in the readme denoting that the color setting is mandatory?

**Comment by malcolmstill** [comment]
@bassnode I just tried iTerm2 (build 1.0.0) and it _is_ picking up and showing the background colour so I'm not sure where your problem is. Obviously make sure your that you've defined "green" (in iTerm2) to be something other than the same colour as the default background. Feel free to post a screen shot with your iTerm2 config; might help me figure out what the issue is.

I'll add something to the readme stating that one really needs to set, as a minimum, the current-item colour to be something other than default.
